#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.8.0
# Product:       ld20
# Model-Version: 2.0.0
#

import pytest
from sensirion_i2c_ld20.device import Ld20Device

from sensirion_i2c_ld20.commands import (InvFlowScaleFactors)


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 3.3
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x08,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Ld20Device(channel)


def test_stop_continuous_measurement1(sensor):
    sensor.stop_continuous_measurement()


def test_read_product_identifier1(sensor):
    (product_identifier, serial_number
     ) = sensor.read_product_identifier()
    print(f"product_identifier: {product_identifier}; "
          f"serial_number: {serial_number}; "
          )


def test_enter_sleep1(sensor):
    sensor.enter_sleep()
    sensor.exit_sleep()


def test_start_continuous_measurement1(sensor):
    sensor.start_continuous_measurement()
    (a_flow, a_temperature, a_signaling_flags
     ) = sensor.read_measurement_data(InvFlowScaleFactors.LD20_0600L)
    print(f"a_flow: {a_flow}; "
          f"a_temperature: {a_temperature}; "
          f"a_signaling_flags: {a_signaling_flags}; "
          )
    sensor.stop_continuous_measurement()

