#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.8.0
# Product:       ld20
# Model-Version: 2.0.0
#
"""
The transfer classes specify the data that is transferred between host and sensor. The generated transfer classes
are used by the driver class and not intended for direct use.
"""

from enum import Enum
from sensirion_driver_adapters.transfer import Transfer
from sensirion_driver_adapters.rx_tx_data import TxData, RxData
from sensirion_driver_support_types.bitfield import BitField, BitfieldContainer


class InvFlowScaleFactors(Enum):
    LD20_0600L = 1200
    LD20_2600B = 20

    def __int__(self):
        return self.value


class SignalingFlagsT(BitfieldContainer):
    air_in_line_flag = BitField(offset=0, width=1)
    high_flow_flag = BitField(offset=1, width=1)
    unused = BitField(offset=2, width=3)
    exp_smoothing_active = BitField(offset=5, width=1)


class ReadMeasurementDataRaw(Transfer):
    """
    After the command *start_h2o_continuous_measurement* has been sent, the chip continuously measures and updates
    the measurement results. New results (flow, temperature, and signaling flags) can be read continuously
    with this command.
    """

    def pack(self):
        return None

    rx = RxData('>hhH')


class StopContinuousMeasurement(Transfer):
    """
    This command stops the continuous measurement and puts the sensor in idle mode.
    After it receives the stop command, the sensor needs up to 0.5ms to power down the heater,
    enter idle mode and be receptive for a new command.
    """

    CMD_ID = 0x3ff9

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>H', device_busy_delay=0.001, slave_address=None, ignore_ack=False)


class EnterSleep(Transfer):
    """
    In sleep mode the sensor uses a minimum amount of power. The mode can only be entered from idle mode,
    i.e. when the sensor is not measuring.
    This mode is particularly useful for battery operated devices. To minimize the current in this mode,
    the complexity of the sleep mode circuit has been reduced as much as possible, which is mainly reflected by
    the way the sensor exits the sleep mode. In sleep mode the sensor cannot be soft reset.
    Supported by products: LD20-0600L, LD20-2600B
    """

    CMD_ID = 0x3677

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>H', device_busy_delay=0.0, slave_address=None, ignore_ack=True)


class ExitSleep(Transfer):
    """
    The sensor exits the sleep mode and enters the idle mode when it receives the valid I2C address and a write
    bit (‘0’).
    Note that the I2C address is not acknowledged. It is necessary to poll the sensor to see whether the sensor has
    received the address and has woken up. This should take typically 25ms.
    Supported by products: LD20-0600L, LD20-2600B
    """

    CMD_ID = 0x0

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>B', device_busy_delay=0.025, slave_address=None, ignore_ack=True)


class ReadProductIdentifierPrepare(Transfer):
    """
    Prepare to read the product identifier and the serial number.
    The command can only be executed from the idle mode, i.e. when the sensor is not performing measurements.
    """

    CMD_ID = 0x367c

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>H')


class ReadProductIdentifier(Transfer):
    """
    This command allows to read product identifier and the serial number.
    The command can only be executed from the idle mode, i.e. when the sensor is not performing measurements
    and *read_product_identifier_prepare* is called before.
    """

    CMD_ID = 0xe102

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>H')
    rx = RxData('>III')


class StartContinuousMeasurement(Transfer):
    """
    Starts continuous measurement mode.
    The sensor measures both the flow rate and the temperature. After the command has been sent, the chip
    continuously measures and updates the measurement results which can be read with *read_measurement_data_raw*.
    """

    CMD_ID = 0x3608

    def pack(self):
        return self.tx_data.pack([])

    tx = TxData(CMD_ID, '>H', device_busy_delay=0.012, slave_address=None, ignore_ack=False)
